
package fr.polytechnancy;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GestEtudiantService", targetNamespace = "http://www.polytechNancy.fr", wsdlLocation = "file:/C:/Users/Mighstye/Documents/GitHub/syst_distrib_begin_berviller/Tp1SoapClientJava/src/GestEtudiantService.wsdl")
public class GestEtudiantService
    extends Service
{

    private final static URL GESTETUDIANTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(fr.polytechnancy.GestEtudiantService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = fr.polytechnancy.GestEtudiantService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8686/wsGestEtudiant/?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8686/wsGestEtudiant/?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GESTETUDIANTSERVICE_WSDL_LOCATION = url;
    }

    public GestEtudiantService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestEtudiantService() {
        super(GESTETUDIANTSERVICE_WSDL_LOCATION, new QName("http://www.polytechNancy.fr", "GestEtudiantService"));
    }

    /**
     * 
     * @return
     *     returns TP1_0020Exercice_0020Gestion_0020Etudiant
     */
    @WebEndpoint(name = "TP1 Exercice Gestion EtudiantPort")
    public TP1_0020Exercice_0020Gestion_0020Etudiant getTP1_0020Exercice_0020Gestion_0020EtudiantPort() {
        return super.getPort(new QName("http://www.polytechNancy.fr", "TP1 Exercice Gestion EtudiantPort"), TP1_0020Exercice_0020Gestion_0020Etudiant.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TP1_0020Exercice_0020Gestion_0020Etudiant
     */
    @WebEndpoint(name = "TP1 Exercice Gestion EtudiantPort")
    public TP1_0020Exercice_0020Gestion_0020Etudiant getTP1_0020Exercice_0020Gestion_0020EtudiantPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytechNancy.fr", "TP1 Exercice Gestion EtudiantPort"), TP1_0020Exercice_0020Gestion_0020Etudiant.class, features);
    }

}
