
package begber.web.servlet.client.gestions;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionsService", targetNamespace = "gestions", wsdlLocation = "file:/C:/Users/Mighstye/eclipse-workspace/test1/src/begber/web/servlet/client/GestionsService.wsdl")
public class GestionsService
    extends Service
{

    private final static URL GESTIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GESTIONSSERVICE_EXCEPTION;
    private final static QName GESTIONSSERVICE_QNAME = new QName("gestions", "GestionsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Mighstye/eclipse-workspace/test1/src/begber/web/servlet/client/GestionsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONSSERVICE_WSDL_LOCATION = url;
        GESTIONSSERVICE_EXCEPTION = e;
    }

    public GestionsService() {
        super(__getWsdlLocation(), GESTIONSSERVICE_QNAME);
    }

    public GestionsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONSSERVICE_QNAME, features);
    }

    public GestionsService(URL wsdlLocation) {
        super(wsdlLocation, GESTIONSSERVICE_QNAME);
    }

    public GestionsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONSSERVICE_QNAME, features);
    }

    public GestionsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProjetGestionEtudiant
     */
    @WebEndpoint(name = "ProjetGestionEtudiantPort")
    public ProjetGestionEtudiant getProjetGestionEtudiantPort() {
        return super.getPort(new QName("gestions", "ProjetGestionEtudiantPort"), ProjetGestionEtudiant.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProjetGestionEtudiant
     */
    @WebEndpoint(name = "ProjetGestionEtudiantPort")
    public ProjetGestionEtudiant getProjetGestionEtudiantPort(WebServiceFeature... features) {
        return super.getPort(new QName("gestions", "ProjetGestionEtudiantPort"), ProjetGestionEtudiant.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONSSERVICE_EXCEPTION!= null) {
            throw GESTIONSSERVICE_EXCEPTION;
        }
        return GESTIONSSERVICE_WSDL_LOCATION;
    }

}
